version: '3'

volumes:
  static:
  database:


services:
  blog_3.6.4:
    build:
      context: .
      dockerfile: compose/production/django/Dockerfile
    image: blog_3.6.4
    container_name: blog_3.6.4
    working_dir: /app
    volumes:
      - database:/app/database
      - static:/app/static
    env_file:
      - .envs/.production
    ports:
      - "8000:8000"
    command: /start.sh

  nginx:
    build:
      context: .
      dockerfile: compose/production/nginx/Dockerfile
    image: blog_3.6.4_nginx
    container_name: blog_3.6.4_nginx
    volumes:
      - static:/apps/blog_3.6.4/static
    ports:
      - "80:80"
      - "443:443"
